export const routes = {
  index: '/',
  login: '/login',
  logout: '/logout',
  explore: '/explore',
  onboarding: '/onboarding',
  searchResults: '/search',
  categories: '/categories',
  category: '/category/:categoryId',
  author: '/author',
  authorBook: '/author-book-api/:id',
  authorDetailProfile: '/author-detail-profile',
  authorsByCategory: '/authors/:genre',
  // contributor: '/contributor',
  book: '/user-recap-detail-item/:id',
  books: '/books',
  recapPlayer: '/recap-item-detail/:recapId',
  playlist: '/playlist',
  viewHistory: '/history',
  confirmEmail: '/confirm-email',
  billing: '/billing',
  billingResult: '/result',
  supportTickets: '/application',
  profileSettings: '/settings',
  forgetPassword: '/forget-password',
  subscriptionHistory: '/subscription-history',
  becomeContributor: '/become-contributor',
}
