export const routes = {
  index: '/',
  login: '/login',
  logout: '/logout',
  explore: '/explore',
  onboarding: '/onboarding',
  bookDetail: '/books/:id',
  books: '/books',
  recapPlayer: '/recap/:recapId',
  playlist: '/playlist',
  viewHistory: '/history',
  confirmEmail: '/confirm-email',
  billing: '/billing',
  billingResult: '/result',
  supportTickets: '/application',
  profileSettings: '/settings',
  forgetPassword: '/forget-password',
  subscriptionHistory: '/subscriptions',
  becomeContributor: '/become-contributor',
}