export const routes = {
  index: '/',
  login: '/login',
  logout: '/logout',
  explore: '/explore',
  onboarding: '/onboarding',
  categories: '/categories',
  categoryDetail: '/category/:categoryId',
  authors: '/authors',
  authorBooks: '/authors/:id',

  // authorDetailProfile: '/author-detail-profile',
  // authorsByCategory: '/authors/:genre',
  // contributor: '/contributor',
  bookDetail: '/books/:id',
  books: '/books',
  recapPlayer: '/recap/:recapId',
  playlist: '/playlist',
  viewHistory: '/history',
  confirmEmail: '/confirm-email',
  billing: '/billing',
  billingResult: '/result',
  supportTickets: '/application',
  profileSettings: '/settings',
  forgetPassword: '/forget-password',
  subscriptionHistory: '/subscriptions',
  becomeContributor: '/become-contributor',
}
